name: Testes de API com HTML Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes e gerar Relatório
        run: npm test

      - name: Upload do relatório HTML como artefato
        uses: actions/upload-artifact@v4
        with:
          name: jest-html-report
          path: reports/test-report.html
